# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.alarm_changed_event import AlarmChangedEvent  # noqa: E501
from swagger_client.rest import ApiException


class TestAlarmChangedEvent(unittest.TestCase):
    """AlarmChangedEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlarmChangedEvent(self):
        """Test AlarmChangedEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.alarm_changed_event.AlarmChangedEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
