# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.portal_users_api import PortalUsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPortalUsersApi(unittest.TestCase):
    """PortalUsersApi unit test stubs"""

    def setUp(self):
        self.api = PortalUsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_portal_user(self):
        """Test case for create_portal_user

        Create new Portal User  # noqa: E501
        """
        pass

    def test_delete_portal_user(self):
        """Test case for delete_portal_user

        Delete PortalUser  # noqa: E501
        """
        pass

    def test_get_portal_user_by_id(self):
        """Test case for get_portal_user_by_id

        Get portal user By Id  # noqa: E501
        """
        pass

    def test_get_portal_user_by_username(self):
        """Test case for get_portal_user_by_username

        Get portal user by user name  # noqa: E501
        """
        pass

    def test_get_portal_users_by_customer_id(self):
        """Test case for get_portal_users_by_customer_id

        Get PortalUsers By customerId  # noqa: E501
        """
        pass

    def test_get_portal_users_by_set_of_ids(self):
        """Test case for get_portal_users_by_set_of_ids

        Get PortalUsers By a set of ids  # noqa: E501
        """
        pass

    def test_get_users_for_username(self):
        """Test case for get_users_for_username

        Get Portal Users for username  # noqa: E501
        """
        pass

    def test_update_portal_user(self):
        """Test case for update_portal_user

        Update PortalUser  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
