# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.customer_api import CustomerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomerApi(unittest.TestCase):
    """CustomerApi unit test stubs"""

    def setUp(self):
        self.api = CustomerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_customer_by_id(self):
        """Test case for get_customer_by_id

        Get Customer By Id  # noqa: E501
        """
        pass

    def test_update_customer(self):
        """Test case for update_customer

        Update Customer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
