# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.location_changed_event import LocationChangedEvent  # noqa: E501
from swagger_client.rest import ApiException


class TestLocationChangedEvent(unittest.TestCase):
    """LocationChangedEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocationChangedEvent(self):
        """Test LocationChangedEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.location_changed_event.LocationChangedEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
