# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.firmware_management_api import FirmwareManagementApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFirmwareManagementApi(unittest.TestCase):
    """FirmwareManagementApi unit test stubs"""

    def setUp(self):
        self.api = FirmwareManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_customer_firmware_track_record(self):
        """Test case for create_customer_firmware_track_record

        Create new CustomerFirmwareTrackRecord  # noqa: E501
        """
        pass

    def test_create_firmware_track_record(self):
        """Test case for create_firmware_track_record

        Create new FirmwareTrackRecord  # noqa: E501
        """
        pass

    def test_create_firmware_version(self):
        """Test case for create_firmware_version

        Create new FirmwareVersion  # noqa: E501
        """
        pass

    def test_delete_customer_firmware_track_record(self):
        """Test case for delete_customer_firmware_track_record

        Delete CustomerFirmwareTrackRecord  # noqa: E501
        """
        pass

    def test_delete_firmware_track_assignment(self):
        """Test case for delete_firmware_track_assignment

        Delete FirmwareTrackAssignment  # noqa: E501
        """
        pass

    def test_delete_firmware_track_record(self):
        """Test case for delete_firmware_track_record

        Delete FirmwareTrackRecord  # noqa: E501
        """
        pass

    def test_delete_firmware_version(self):
        """Test case for delete_firmware_version

        Delete FirmwareVersion  # noqa: E501
        """
        pass

    def test_get_customer_firmware_track_record(self):
        """Test case for get_customer_firmware_track_record

        Get CustomerFirmwareTrackRecord By customerId  # noqa: E501
        """
        pass

    def test_get_default_customer_track_setting(self):
        """Test case for get_default_customer_track_setting

        Get default settings for handling automatic firmware upgrades  # noqa: E501
        """
        pass

    def test_get_firmware_model_ids_by_equipment_type(self):
        """Test case for get_firmware_model_ids_by_equipment_type

        Get equipment models from all known firmware versions filtered by equipmentType  # noqa: E501
        """
        pass

    def test_get_firmware_track_assignment_details(self):
        """Test case for get_firmware_track_assignment_details

        Get FirmwareTrackAssignmentDetails for a given firmware track name  # noqa: E501
        """
        pass

    def test_get_firmware_track_record(self):
        """Test case for get_firmware_track_record

        Get FirmwareTrackRecord By Id  # noqa: E501
        """
        pass

    def test_get_firmware_track_record_by_name(self):
        """Test case for get_firmware_track_record_by_name

        Get FirmwareTrackRecord By name  # noqa: E501
        """
        pass

    def test_get_firmware_version(self):
        """Test case for get_firmware_version

        Get FirmwareVersion By Id  # noqa: E501
        """
        pass

    def test_get_firmware_version_by_equipment_type(self):
        """Test case for get_firmware_version_by_equipment_type

        Get FirmwareVersions filtered by equipmentType and optional equipment model  # noqa: E501
        """
        pass

    def test_get_firmware_version_by_name(self):
        """Test case for get_firmware_version_by_name

        Get FirmwareVersion By name  # noqa: E501
        """
        pass

    def test_update_customer_firmware_track_record(self):
        """Test case for update_customer_firmware_track_record

        Update CustomerFirmwareTrackRecord  # noqa: E501
        """
        pass

    def test_update_firmware_track_assignment_details(self):
        """Test case for update_firmware_track_assignment_details

        Update FirmwareTrackAssignmentDetails  # noqa: E501
        """
        pass

    def test_update_firmware_track_record(self):
        """Test case for update_firmware_track_record

        Update FirmwareTrackRecord  # noqa: E501
        """
        pass

    def test_update_firmware_version(self):
        """Test case for update_firmware_version

        Update FirmwareVersion  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
