# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.file_services_api import FileServicesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFileServicesApi(unittest.TestCase):
    """FileServicesApi unit test stubs"""

    def setUp(self):
        self.api = FileServicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_binary_file(self):
        """Test case for download_binary_file

        Download binary file.  # noqa: E501
        """
        pass

    def test_upload_binary_file(self):
        """Test case for upload_binary_file

        Upload binary file.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
