# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.service_adoption_metrics_api import ServiceAdoptionMetricsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceAdoptionMetricsApi(unittest.TestCase):
    """ServiceAdoptionMetricsApi unit test stubs"""

    def setUp(self):
        self.api = ServiceAdoptionMetricsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_adoption_metrics_all_per_day(self):
        """Test case for get_adoption_metrics_all_per_day

        Get daily service adoption metrics for a given year  # noqa: E501
        """
        pass

    def test_get_adoption_metrics_all_per_month(self):
        """Test case for get_adoption_metrics_all_per_month

        Get monthly service adoption metrics for a given year  # noqa: E501
        """
        pass

    def test_get_adoption_metrics_all_per_week(self):
        """Test case for get_adoption_metrics_all_per_week

        Get weekly service adoption metrics for a given year  # noqa: E501
        """
        pass

    def test_get_adoption_metrics_per_customer_per_day(self):
        """Test case for get_adoption_metrics_per_customer_per_day

        Get daily service adoption metrics for a given year aggregated by customer and filtered by specified customer ids  # noqa: E501
        """
        pass

    def test_get_adoption_metrics_per_equipment_per_day(self):
        """Test case for get_adoption_metrics_per_equipment_per_day

        Get daily service adoption metrics for a given year filtered by specified equipment ids  # noqa: E501
        """
        pass

    def test_get_adoption_metrics_per_location_per_day(self):
        """Test case for get_adoption_metrics_per_location_per_day

        Get daily service adoption metrics for a given year aggregated by location and filtered by specified location ids  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
