#!/bin/bash

set +e
which aws || true
if command -v aws >/dev/null ; then
    rm -f awscliv2.zip
fi
if [ -f "awscliv2.zip" ]; then
    unzip -q awscliv2.zip
    sudo ./aws/install
    echo -n "Installed AWS CLI -> "
    which aws
    aws --version
fi
if [ -f "kubectl.gz" ]; then
    # this is version 1.36.1
    gunzip kubectl.gz && \
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
        echo "Installed kubectl -> /usr/local/bin/kubectl"
    /usr/local/bin/kubectl version --client=true
fi
