# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClientAuthEvent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'model_type': 'str',
        'all_of': 'RealTimeEvent',
        'session_id': 'int',
        'ssid': 'str',
        'client_mac_address': 'MacAddress',
        'radio_type': 'RadioType',
        'is_reassociation': 'bool',
        'auth_status': 'WlanStatusCode'
    }

    attribute_map = {
        'model_type': 'model_type',
        'all_of': 'allOf',
        'session_id': 'sessionId',
        'ssid': 'ssid',
        'client_mac_address': 'clientMacAddress',
        'radio_type': 'radioType',
        'is_reassociation': 'isReassociation',
        'auth_status': 'authStatus'
    }

    def __init__(self, model_type=None, all_of=None, session_id=None, ssid=None, client_mac_address=None, radio_type=None, is_reassociation=None, auth_status=None):  # noqa: E501
        """ClientAuthEvent - a model defined in Swagger"""  # noqa: E501
        self._model_type = None
        self._all_of = None
        self._session_id = None
        self._ssid = None
        self._client_mac_address = None
        self._radio_type = None
        self._is_reassociation = None
        self._auth_status = None
        self.discriminator = None
        self.model_type = model_type
        if all_of is not None:
            self.all_of = all_of
        if session_id is not None:
            self.session_id = session_id
        if ssid is not None:
            self.ssid = ssid
        if client_mac_address is not None:
            self.client_mac_address = client_mac_address
        if radio_type is not None:
            self.radio_type = radio_type
        if is_reassociation is not None:
            self.is_reassociation = is_reassociation
        if auth_status is not None:
            self.auth_status = auth_status

    @property
    def model_type(self):
        """Gets the model_type of this ClientAuthEvent.  # noqa: E501


        :return: The model_type of this ClientAuthEvent.  # noqa: E501
        :rtype: str
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type):
        """Sets the model_type of this ClientAuthEvent.


        :param model_type: The model_type of this ClientAuthEvent.  # noqa: E501
        :type: str
        """
        if model_type is None:
            raise ValueError("Invalid value for `model_type`, must not be `None`")  # noqa: E501

        self._model_type = model_type

    @property
    def all_of(self):
        """Gets the all_of of this ClientAuthEvent.  # noqa: E501


        :return: The all_of of this ClientAuthEvent.  # noqa: E501
        :rtype: RealTimeEvent
        """
        return self._all_of

    @all_of.setter
    def all_of(self, all_of):
        """Sets the all_of of this ClientAuthEvent.


        :param all_of: The all_of of this ClientAuthEvent.  # noqa: E501
        :type: RealTimeEvent
        """

        self._all_of = all_of

    @property
    def session_id(self):
        """Gets the session_id of this ClientAuthEvent.  # noqa: E501


        :return: The session_id of this ClientAuthEvent.  # noqa: E501
        :rtype: int
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this ClientAuthEvent.


        :param session_id: The session_id of this ClientAuthEvent.  # noqa: E501
        :type: int
        """

        self._session_id = session_id

    @property
    def ssid(self):
        """Gets the ssid of this ClientAuthEvent.  # noqa: E501


        :return: The ssid of this ClientAuthEvent.  # noqa: E501
        :rtype: str
        """
        return self._ssid

    @ssid.setter
    def ssid(self, ssid):
        """Sets the ssid of this ClientAuthEvent.


        :param ssid: The ssid of this ClientAuthEvent.  # noqa: E501
        :type: str
        """

        self._ssid = ssid

    @property
    def client_mac_address(self):
        """Gets the client_mac_address of this ClientAuthEvent.  # noqa: E501


        :return: The client_mac_address of this ClientAuthEvent.  # noqa: E501
        :rtype: MacAddress
        """
        return self._client_mac_address

    @client_mac_address.setter
    def client_mac_address(self, client_mac_address):
        """Sets the client_mac_address of this ClientAuthEvent.


        :param client_mac_address: The client_mac_address of this ClientAuthEvent.  # noqa: E501
        :type: MacAddress
        """

        self._client_mac_address = client_mac_address

    @property
    def radio_type(self):
        """Gets the radio_type of this ClientAuthEvent.  # noqa: E501


        :return: The radio_type of this ClientAuthEvent.  # noqa: E501
        :rtype: RadioType
        """
        return self._radio_type

    @radio_type.setter
    def radio_type(self, radio_type):
        """Sets the radio_type of this ClientAuthEvent.


        :param radio_type: The radio_type of this ClientAuthEvent.  # noqa: E501
        :type: RadioType
        """

        self._radio_type = radio_type

    @property
    def is_reassociation(self):
        """Gets the is_reassociation of this ClientAuthEvent.  # noqa: E501


        :return: The is_reassociation of this ClientAuthEvent.  # noqa: E501
        :rtype: bool
        """
        return self._is_reassociation

    @is_reassociation.setter
    def is_reassociation(self, is_reassociation):
        """Sets the is_reassociation of this ClientAuthEvent.


        :param is_reassociation: The is_reassociation of this ClientAuthEvent.  # noqa: E501
        :type: bool
        """

        self._is_reassociation = is_reassociation

    @property
    def auth_status(self):
        """Gets the auth_status of this ClientAuthEvent.  # noqa: E501


        :return: The auth_status of this ClientAuthEvent.  # noqa: E501
        :rtype: WlanStatusCode
        """
        return self._auth_status

    @auth_status.setter
    def auth_status(self, auth_status):
        """Sets the auth_status of this ClientAuthEvent.


        :param auth_status: The auth_status of this ClientAuthEvent.  # noqa: E501
        :type: WlanStatusCode
        """

        self._auth_status = auth_status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClientAuthEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClientAuthEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
