# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EquipmentPerformanceDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'avg_free_memory': 'int',
        'avg_cpu_util_core1': 'int',
        'avg_cpu_util_core2': 'int',
        'avg_cpu_temperature': 'int'
    }

    attribute_map = {
        'avg_free_memory': 'avgFreeMemory',
        'avg_cpu_util_core1': 'avgCpuUtilCore1',
        'avg_cpu_util_core2': 'avgCpuUtilCore2',
        'avg_cpu_temperature': 'avgCpuTemperature'
    }

    def __init__(self, avg_free_memory=None, avg_cpu_util_core1=None, avg_cpu_util_core2=None, avg_cpu_temperature=None):  # noqa: E501
        """EquipmentPerformanceDetails - a model defined in Swagger"""  # noqa: E501
        self._avg_free_memory = None
        self._avg_cpu_util_core1 = None
        self._avg_cpu_util_core2 = None
        self._avg_cpu_temperature = None
        self.discriminator = None
        if avg_free_memory is not None:
            self.avg_free_memory = avg_free_memory
        if avg_cpu_util_core1 is not None:
            self.avg_cpu_util_core1 = avg_cpu_util_core1
        if avg_cpu_util_core2 is not None:
            self.avg_cpu_util_core2 = avg_cpu_util_core2
        if avg_cpu_temperature is not None:
            self.avg_cpu_temperature = avg_cpu_temperature

    @property
    def avg_free_memory(self):
        """Gets the avg_free_memory of this EquipmentPerformanceDetails.  # noqa: E501


        :return: The avg_free_memory of this EquipmentPerformanceDetails.  # noqa: E501
        :rtype: int
        """
        return self._avg_free_memory

    @avg_free_memory.setter
    def avg_free_memory(self, avg_free_memory):
        """Sets the avg_free_memory of this EquipmentPerformanceDetails.


        :param avg_free_memory: The avg_free_memory of this EquipmentPerformanceDetails.  # noqa: E501
        :type: int
        """

        self._avg_free_memory = avg_free_memory

    @property
    def avg_cpu_util_core1(self):
        """Gets the avg_cpu_util_core1 of this EquipmentPerformanceDetails.  # noqa: E501


        :return: The avg_cpu_util_core1 of this EquipmentPerformanceDetails.  # noqa: E501
        :rtype: int
        """
        return self._avg_cpu_util_core1

    @avg_cpu_util_core1.setter
    def avg_cpu_util_core1(self, avg_cpu_util_core1):
        """Sets the avg_cpu_util_core1 of this EquipmentPerformanceDetails.


        :param avg_cpu_util_core1: The avg_cpu_util_core1 of this EquipmentPerformanceDetails.  # noqa: E501
        :type: int
        """

        self._avg_cpu_util_core1 = avg_cpu_util_core1

    @property
    def avg_cpu_util_core2(self):
        """Gets the avg_cpu_util_core2 of this EquipmentPerformanceDetails.  # noqa: E501


        :return: The avg_cpu_util_core2 of this EquipmentPerformanceDetails.  # noqa: E501
        :rtype: int
        """
        return self._avg_cpu_util_core2

    @avg_cpu_util_core2.setter
    def avg_cpu_util_core2(self, avg_cpu_util_core2):
        """Sets the avg_cpu_util_core2 of this EquipmentPerformanceDetails.


        :param avg_cpu_util_core2: The avg_cpu_util_core2 of this EquipmentPerformanceDetails.  # noqa: E501
        :type: int
        """

        self._avg_cpu_util_core2 = avg_cpu_util_core2

    @property
    def avg_cpu_temperature(self):
        """Gets the avg_cpu_temperature of this EquipmentPerformanceDetails.  # noqa: E501


        :return: The avg_cpu_temperature of this EquipmentPerformanceDetails.  # noqa: E501
        :rtype: int
        """
        return self._avg_cpu_temperature

    @avg_cpu_temperature.setter
    def avg_cpu_temperature(self, avg_cpu_temperature):
        """Sets the avg_cpu_temperature of this EquipmentPerformanceDetails.


        :param avg_cpu_temperature: The avg_cpu_temperature of this EquipmentPerformanceDetails.  # noqa: E501
        :type: int
        """

        self._avg_cpu_temperature = avg_cpu_temperature

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EquipmentPerformanceDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EquipmentPerformanceDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
