# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GreTunnelConfiguration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gre_tunnel_name': 'str',
        'gre_remote_inet_addr': 'str',
        'vlan_ids_in_gre_tunnel': 'list[int]'
    }

    attribute_map = {
        'gre_tunnel_name': 'greTunnelName',
        'gre_remote_inet_addr': 'greRemoteInetAddr',
        'vlan_ids_in_gre_tunnel': 'vlanIdsInGreTunnel'
    }

    def __init__(self, gre_tunnel_name=None, gre_remote_inet_addr=None, vlan_ids_in_gre_tunnel=None):  # noqa: E501
        """GreTunnelConfiguration - a model defined in Swagger"""  # noqa: E501
        self._gre_tunnel_name = None
        self._gre_remote_inet_addr = None
        self._vlan_ids_in_gre_tunnel = None
        self.discriminator = None
        if gre_tunnel_name is not None:
            self.gre_tunnel_name = gre_tunnel_name
        if gre_remote_inet_addr is not None:
            self.gre_remote_inet_addr = gre_remote_inet_addr
        if vlan_ids_in_gre_tunnel is not None:
            self.vlan_ids_in_gre_tunnel = vlan_ids_in_gre_tunnel

    @property
    def gre_tunnel_name(self):
        """Gets the gre_tunnel_name of this GreTunnelConfiguration.  # noqa: E501


        :return: The gre_tunnel_name of this GreTunnelConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._gre_tunnel_name

    @gre_tunnel_name.setter
    def gre_tunnel_name(self, gre_tunnel_name):
        """Sets the gre_tunnel_name of this GreTunnelConfiguration.


        :param gre_tunnel_name: The gre_tunnel_name of this GreTunnelConfiguration.  # noqa: E501
        :type: str
        """

        self._gre_tunnel_name = gre_tunnel_name

    @property
    def gre_remote_inet_addr(self):
        """Gets the gre_remote_inet_addr of this GreTunnelConfiguration.  # noqa: E501


        :return: The gre_remote_inet_addr of this GreTunnelConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._gre_remote_inet_addr

    @gre_remote_inet_addr.setter
    def gre_remote_inet_addr(self, gre_remote_inet_addr):
        """Sets the gre_remote_inet_addr of this GreTunnelConfiguration.


        :param gre_remote_inet_addr: The gre_remote_inet_addr of this GreTunnelConfiguration.  # noqa: E501
        :type: str
        """

        self._gre_remote_inet_addr = gre_remote_inet_addr

    @property
    def vlan_ids_in_gre_tunnel(self):
        """Gets the vlan_ids_in_gre_tunnel of this GreTunnelConfiguration.  # noqa: E501


        :return: The vlan_ids_in_gre_tunnel of this GreTunnelConfiguration.  # noqa: E501
        :rtype: list[int]
        """
        return self._vlan_ids_in_gre_tunnel

    @vlan_ids_in_gre_tunnel.setter
    def vlan_ids_in_gre_tunnel(self, vlan_ids_in_gre_tunnel):
        """Sets the vlan_ids_in_gre_tunnel of this GreTunnelConfiguration.


        :param vlan_ids_in_gre_tunnel: The vlan_ids_in_gre_tunnel of this GreTunnelConfiguration.  # noqa: E501
        :type: list[int]
        """

        self._vlan_ids_in_gre_tunnel = vlan_ids_in_gre_tunnel

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GreTunnelConfiguration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GreTunnelConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
