# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LocationActivityDetailsMap(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sunday': 'LocationActivityDetails',
        'monday': 'LocationActivityDetails',
        'tuesday': 'LocationActivityDetails',
        'wednesday': 'LocationActivityDetails',
        'thursday': 'LocationActivityDetails',
        'friday': 'LocationActivityDetails',
        'saturday': 'LocationActivityDetails'
    }

    attribute_map = {
        'sunday': 'SUNDAY',
        'monday': 'MONDAY',
        'tuesday': 'TUESDAY',
        'wednesday': 'WEDNESDAY',
        'thursday': 'THURSDAY',
        'friday': 'FRIDAY',
        'saturday': 'SATURDAY'
    }

    def __init__(self, sunday=None, monday=None, tuesday=None, wednesday=None, thursday=None, friday=None, saturday=None):  # noqa: E501
        """LocationActivityDetailsMap - a model defined in Swagger"""  # noqa: E501
        self._sunday = None
        self._monday = None
        self._tuesday = None
        self._wednesday = None
        self._thursday = None
        self._friday = None
        self._saturday = None
        self.discriminator = None
        if sunday is not None:
            self.sunday = sunday
        if monday is not None:
            self.monday = monday
        if tuesday is not None:
            self.tuesday = tuesday
        if wednesday is not None:
            self.wednesday = wednesday
        if thursday is not None:
            self.thursday = thursday
        if friday is not None:
            self.friday = friday
        if saturday is not None:
            self.saturday = saturday

    @property
    def sunday(self):
        """Gets the sunday of this LocationActivityDetailsMap.  # noqa: E501


        :return: The sunday of this LocationActivityDetailsMap.  # noqa: E501
        :rtype: LocationActivityDetails
        """
        return self._sunday

    @sunday.setter
    def sunday(self, sunday):
        """Sets the sunday of this LocationActivityDetailsMap.


        :param sunday: The sunday of this LocationActivityDetailsMap.  # noqa: E501
        :type: LocationActivityDetails
        """

        self._sunday = sunday

    @property
    def monday(self):
        """Gets the monday of this LocationActivityDetailsMap.  # noqa: E501


        :return: The monday of this LocationActivityDetailsMap.  # noqa: E501
        :rtype: LocationActivityDetails
        """
        return self._monday

    @monday.setter
    def monday(self, monday):
        """Sets the monday of this LocationActivityDetailsMap.


        :param monday: The monday of this LocationActivityDetailsMap.  # noqa: E501
        :type: LocationActivityDetails
        """

        self._monday = monday

    @property
    def tuesday(self):
        """Gets the tuesday of this LocationActivityDetailsMap.  # noqa: E501


        :return: The tuesday of this LocationActivityDetailsMap.  # noqa: E501
        :rtype: LocationActivityDetails
        """
        return self._tuesday

    @tuesday.setter
    def tuesday(self, tuesday):
        """Sets the tuesday of this LocationActivityDetailsMap.


        :param tuesday: The tuesday of this LocationActivityDetailsMap.  # noqa: E501
        :type: LocationActivityDetails
        """

        self._tuesday = tuesday

    @property
    def wednesday(self):
        """Gets the wednesday of this LocationActivityDetailsMap.  # noqa: E501


        :return: The wednesday of this LocationActivityDetailsMap.  # noqa: E501
        :rtype: LocationActivityDetails
        """
        return self._wednesday

    @wednesday.setter
    def wednesday(self, wednesday):
        """Sets the wednesday of this LocationActivityDetailsMap.


        :param wednesday: The wednesday of this LocationActivityDetailsMap.  # noqa: E501
        :type: LocationActivityDetails
        """

        self._wednesday = wednesday

    @property
    def thursday(self):
        """Gets the thursday of this LocationActivityDetailsMap.  # noqa: E501


        :return: The thursday of this LocationActivityDetailsMap.  # noqa: E501
        :rtype: LocationActivityDetails
        """
        return self._thursday

    @thursday.setter
    def thursday(self, thursday):
        """Sets the thursday of this LocationActivityDetailsMap.


        :param thursday: The thursday of this LocationActivityDetailsMap.  # noqa: E501
        :type: LocationActivityDetails
        """

        self._thursday = thursday

    @property
    def friday(self):
        """Gets the friday of this LocationActivityDetailsMap.  # noqa: E501


        :return: The friday of this LocationActivityDetailsMap.  # noqa: E501
        :rtype: LocationActivityDetails
        """
        return self._friday

    @friday.setter
    def friday(self, friday):
        """Sets the friday of this LocationActivityDetailsMap.


        :param friday: The friday of this LocationActivityDetailsMap.  # noqa: E501
        :type: LocationActivityDetails
        """

        self._friday = friday

    @property
    def saturday(self):
        """Gets the saturday of this LocationActivityDetailsMap.  # noqa: E501


        :return: The saturday of this LocationActivityDetailsMap.  # noqa: E501
        :rtype: LocationActivityDetails
        """
        return self._saturday

    @saturday.setter
    def saturday(self, saturday):
        """Sets the saturday of this LocationActivityDetailsMap.


        :param saturday: The saturday of this LocationActivityDetailsMap.  # noqa: E501
        :type: LocationActivityDetails
        """

        self._saturday = saturday

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LocationActivityDetailsMap, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LocationActivityDetailsMap):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
