# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MeshGroupMember(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mash_mode': 'ApMeshMode',
        'equipment_id': 'int',
        'created_timestamp': 'int',
        'last_modified_timestamp': 'int'
    }

    attribute_map = {
        'mash_mode': 'mashMode',
        'equipment_id': 'equipmentId',
        'created_timestamp': 'createdTimestamp',
        'last_modified_timestamp': 'lastModifiedTimestamp'
    }

    def __init__(self, mash_mode=None, equipment_id=None, created_timestamp=None, last_modified_timestamp=None):  # noqa: E501
        """MeshGroupMember - a model defined in Swagger"""  # noqa: E501
        self._mash_mode = None
        self._equipment_id = None
        self._created_timestamp = None
        self._last_modified_timestamp = None
        self.discriminator = None
        if mash_mode is not None:
            self.mash_mode = mash_mode
        if equipment_id is not None:
            self.equipment_id = equipment_id
        if created_timestamp is not None:
            self.created_timestamp = created_timestamp
        if last_modified_timestamp is not None:
            self.last_modified_timestamp = last_modified_timestamp

    @property
    def mash_mode(self):
        """Gets the mash_mode of this MeshGroupMember.  # noqa: E501


        :return: The mash_mode of this MeshGroupMember.  # noqa: E501
        :rtype: ApMeshMode
        """
        return self._mash_mode

    @mash_mode.setter
    def mash_mode(self, mash_mode):
        """Sets the mash_mode of this MeshGroupMember.


        :param mash_mode: The mash_mode of this MeshGroupMember.  # noqa: E501
        :type: ApMeshMode
        """

        self._mash_mode = mash_mode

    @property
    def equipment_id(self):
        """Gets the equipment_id of this MeshGroupMember.  # noqa: E501


        :return: The equipment_id of this MeshGroupMember.  # noqa: E501
        :rtype: int
        """
        return self._equipment_id

    @equipment_id.setter
    def equipment_id(self, equipment_id):
        """Sets the equipment_id of this MeshGroupMember.


        :param equipment_id: The equipment_id of this MeshGroupMember.  # noqa: E501
        :type: int
        """

        self._equipment_id = equipment_id

    @property
    def created_timestamp(self):
        """Gets the created_timestamp of this MeshGroupMember.  # noqa: E501


        :return: The created_timestamp of this MeshGroupMember.  # noqa: E501
        :rtype: int
        """
        return self._created_timestamp

    @created_timestamp.setter
    def created_timestamp(self, created_timestamp):
        """Sets the created_timestamp of this MeshGroupMember.


        :param created_timestamp: The created_timestamp of this MeshGroupMember.  # noqa: E501
        :type: int
        """

        self._created_timestamp = created_timestamp

    @property
    def last_modified_timestamp(self):
        """Gets the last_modified_timestamp of this MeshGroupMember.  # noqa: E501


        :return: The last_modified_timestamp of this MeshGroupMember.  # noqa: E501
        :rtype: int
        """
        return self._last_modified_timestamp

    @last_modified_timestamp.setter
    def last_modified_timestamp(self, last_modified_timestamp):
        """Sets the last_modified_timestamp of this MeshGroupMember.


        :param last_modified_timestamp: The last_modified_timestamp of this MeshGroupMember.  # noqa: E501
        :type: int
        """

        self._last_modified_timestamp = last_modified_timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MeshGroupMember, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MeshGroupMember):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
