# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MinMaxAvgValueInt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'min_value': 'int',
        'max_value': 'int',
        'avg_value': 'int'
    }

    attribute_map = {
        'min_value': 'minValue',
        'max_value': 'maxValue',
        'avg_value': 'avgValue'
    }

    def __init__(self, min_value=None, max_value=None, avg_value=None):  # noqa: E501
        """MinMaxAvgValueInt - a model defined in Swagger"""  # noqa: E501
        self._min_value = None
        self._max_value = None
        self._avg_value = None
        self.discriminator = None
        if min_value is not None:
            self.min_value = min_value
        if max_value is not None:
            self.max_value = max_value
        if avg_value is not None:
            self.avg_value = avg_value

    @property
    def min_value(self):
        """Gets the min_value of this MinMaxAvgValueInt.  # noqa: E501


        :return: The min_value of this MinMaxAvgValueInt.  # noqa: E501
        :rtype: int
        """
        return self._min_value

    @min_value.setter
    def min_value(self, min_value):
        """Sets the min_value of this MinMaxAvgValueInt.


        :param min_value: The min_value of this MinMaxAvgValueInt.  # noqa: E501
        :type: int
        """

        self._min_value = min_value

    @property
    def max_value(self):
        """Gets the max_value of this MinMaxAvgValueInt.  # noqa: E501


        :return: The max_value of this MinMaxAvgValueInt.  # noqa: E501
        :rtype: int
        """
        return self._max_value

    @max_value.setter
    def max_value(self, max_value):
        """Sets the max_value of this MinMaxAvgValueInt.


        :param max_value: The max_value of this MinMaxAvgValueInt.  # noqa: E501
        :type: int
        """

        self._max_value = max_value

    @property
    def avg_value(self):
        """Gets the avg_value of this MinMaxAvgValueInt.  # noqa: E501


        :return: The avg_value of this MinMaxAvgValueInt.  # noqa: E501
        :rtype: int
        """
        return self._avg_value

    @avg_value.setter
    def avg_value(self, avg_value):
        """Sets the avg_value of this MinMaxAvgValueInt.


        :param avg_value: The avg_value of this MinMaxAvgValueInt.  # noqa: E501
        :type: int
        """

        self._avg_value = avg_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MinMaxAvgValueInt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MinMaxAvgValueInt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
