# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NeighbouringAPListConfiguration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'min_signal': 'int',
        'max_aps': 'int'
    }

    attribute_map = {
        'min_signal': 'minSignal',
        'max_aps': 'maxAps'
    }

    def __init__(self, min_signal=None, max_aps=None):  # noqa: E501
        """NeighbouringAPListConfiguration - a model defined in Swagger"""  # noqa: E501
        self._min_signal = None
        self._max_aps = None
        self.discriminator = None
        if min_signal is not None:
            self.min_signal = min_signal
        if max_aps is not None:
            self.max_aps = max_aps

    @property
    def min_signal(self):
        """Gets the min_signal of this NeighbouringAPListConfiguration.  # noqa: E501


        :return: The min_signal of this NeighbouringAPListConfiguration.  # noqa: E501
        :rtype: int
        """
        return self._min_signal

    @min_signal.setter
    def min_signal(self, min_signal):
        """Sets the min_signal of this NeighbouringAPListConfiguration.


        :param min_signal: The min_signal of this NeighbouringAPListConfiguration.  # noqa: E501
        :type: int
        """

        self._min_signal = min_signal

    @property
    def max_aps(self):
        """Gets the max_aps of this NeighbouringAPListConfiguration.  # noqa: E501


        :return: The max_aps of this NeighbouringAPListConfiguration.  # noqa: E501
        :rtype: int
        """
        return self._max_aps

    @max_aps.setter
    def max_aps(self, max_aps):
        """Sets the max_aps of this NeighbouringAPListConfiguration.


        :param max_aps: The max_aps of this NeighbouringAPListConfiguration.  # noqa: E501
        :type: int
        """

        self._max_aps = max_aps

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NeighbouringAPListConfiguration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NeighbouringAPListConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
