# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PairLongLong(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'value1': 'int',
        'value2': 'int'
    }

    attribute_map = {
        'value1': 'value1',
        'value2': 'value2'
    }

    def __init__(self, value1=None, value2=None):  # noqa: E501
        """PairLongLong - a model defined in Swagger"""  # noqa: E501
        self._value1 = None
        self._value2 = None
        self.discriminator = None
        if value1 is not None:
            self.value1 = value1
        if value2 is not None:
            self.value2 = value2

    @property
    def value1(self):
        """Gets the value1 of this PairLongLong.  # noqa: E501


        :return: The value1 of this PairLongLong.  # noqa: E501
        :rtype: int
        """
        return self._value1

    @value1.setter
    def value1(self, value1):
        """Sets the value1 of this PairLongLong.


        :param value1: The value1 of this PairLongLong.  # noqa: E501
        :type: int
        """

        self._value1 = value1

    @property
    def value2(self):
        """Gets the value2 of this PairLongLong.  # noqa: E501


        :return: The value2 of this PairLongLong.  # noqa: E501
        :rtype: int
        """
        return self._value2

    @value2.setter
    def value2(self, value2):
        """Sets the value2 of this PairLongLong.


        :param value2: The value2 of this PairLongLong.  # noqa: E501
        :type: int
        """

        self._value2 = value2

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PairLongLong, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PairLongLong):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
