# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RealTimeSipCallReportEvent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'model_type': 'str',
        'all_of': 'RealTimeSipCallEventWithStats',
        'report_reason': 'SIPCallReportReason'
    }

    attribute_map = {
        'model_type': 'model_type',
        'all_of': 'allOf',
        'report_reason': 'reportReason'
    }

    def __init__(self, model_type=None, all_of=None, report_reason=None):  # noqa: E501
        """RealTimeSipCallReportEvent - a model defined in Swagger"""  # noqa: E501
        self._model_type = None
        self._all_of = None
        self._report_reason = None
        self.discriminator = None
        self.model_type = model_type
        if all_of is not None:
            self.all_of = all_of
        if report_reason is not None:
            self.report_reason = report_reason

    @property
    def model_type(self):
        """Gets the model_type of this RealTimeSipCallReportEvent.  # noqa: E501


        :return: The model_type of this RealTimeSipCallReportEvent.  # noqa: E501
        :rtype: str
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type):
        """Sets the model_type of this RealTimeSipCallReportEvent.


        :param model_type: The model_type of this RealTimeSipCallReportEvent.  # noqa: E501
        :type: str
        """
        if model_type is None:
            raise ValueError("Invalid value for `model_type`, must not be `None`")  # noqa: E501

        self._model_type = model_type

    @property
    def all_of(self):
        """Gets the all_of of this RealTimeSipCallReportEvent.  # noqa: E501


        :return: The all_of of this RealTimeSipCallReportEvent.  # noqa: E501
        :rtype: RealTimeSipCallEventWithStats
        """
        return self._all_of

    @all_of.setter
    def all_of(self, all_of):
        """Sets the all_of of this RealTimeSipCallReportEvent.


        :param all_of: The all_of of this RealTimeSipCallReportEvent.  # noqa: E501
        :type: RealTimeSipCallEventWithStats
        """

        self._all_of = all_of

    @property
    def report_reason(self):
        """Gets the report_reason of this RealTimeSipCallReportEvent.  # noqa: E501


        :return: The report_reason of this RealTimeSipCallReportEvent.  # noqa: E501
        :rtype: SIPCallReportReason
        """
        return self._report_reason

    @report_reason.setter
    def report_reason(self, report_reason):
        """Sets the report_reason of this RealTimeSipCallReportEvent.


        :param report_reason: The report_reason of this RealTimeSipCallReportEvent.  # noqa: E501
        :type: SIPCallReportReason
        """

        self._report_reason = report_reason

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RealTimeSipCallReportEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RealTimeSipCallReportEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
