# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RealTimeSipCallStartEvent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'model_type': 'str',
        'all_of': 'RealTimeEvent',
        'sip_call_id': 'int',
        'association_id': 'int',
        'mac_address': 'MacAddress',
        'radio_type': 'RadioType',
        'channel': 'int',
        'codecs': 'list[str]',
        'provider_domain': 'str',
        'device_info': 'str'
    }

    attribute_map = {
        'model_type': 'model_type',
        'all_of': 'allOf',
        'sip_call_id': 'sipCallId',
        'association_id': 'associationId',
        'mac_address': 'macAddress',
        'radio_type': 'radioType',
        'channel': 'channel',
        'codecs': 'codecs',
        'provider_domain': 'providerDomain',
        'device_info': 'deviceInfo'
    }

    def __init__(self, model_type=None, all_of=None, sip_call_id=None, association_id=None, mac_address=None, radio_type=None, channel=None, codecs=None, provider_domain=None, device_info=None):  # noqa: E501
        """RealTimeSipCallStartEvent - a model defined in Swagger"""  # noqa: E501
        self._model_type = None
        self._all_of = None
        self._sip_call_id = None
        self._association_id = None
        self._mac_address = None
        self._radio_type = None
        self._channel = None
        self._codecs = None
        self._provider_domain = None
        self._device_info = None
        self.discriminator = None
        self.model_type = model_type
        if all_of is not None:
            self.all_of = all_of
        if sip_call_id is not None:
            self.sip_call_id = sip_call_id
        if association_id is not None:
            self.association_id = association_id
        if mac_address is not None:
            self.mac_address = mac_address
        if radio_type is not None:
            self.radio_type = radio_type
        if channel is not None:
            self.channel = channel
        if codecs is not None:
            self.codecs = codecs
        if provider_domain is not None:
            self.provider_domain = provider_domain
        if device_info is not None:
            self.device_info = device_info

    @property
    def model_type(self):
        """Gets the model_type of this RealTimeSipCallStartEvent.  # noqa: E501


        :return: The model_type of this RealTimeSipCallStartEvent.  # noqa: E501
        :rtype: str
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type):
        """Sets the model_type of this RealTimeSipCallStartEvent.


        :param model_type: The model_type of this RealTimeSipCallStartEvent.  # noqa: E501
        :type: str
        """
        if model_type is None:
            raise ValueError("Invalid value for `model_type`, must not be `None`")  # noqa: E501

        self._model_type = model_type

    @property
    def all_of(self):
        """Gets the all_of of this RealTimeSipCallStartEvent.  # noqa: E501


        :return: The all_of of this RealTimeSipCallStartEvent.  # noqa: E501
        :rtype: RealTimeEvent
        """
        return self._all_of

    @all_of.setter
    def all_of(self, all_of):
        """Sets the all_of of this RealTimeSipCallStartEvent.


        :param all_of: The all_of of this RealTimeSipCallStartEvent.  # noqa: E501
        :type: RealTimeEvent
        """

        self._all_of = all_of

    @property
    def sip_call_id(self):
        """Gets the sip_call_id of this RealTimeSipCallStartEvent.  # noqa: E501


        :return: The sip_call_id of this RealTimeSipCallStartEvent.  # noqa: E501
        :rtype: int
        """
        return self._sip_call_id

    @sip_call_id.setter
    def sip_call_id(self, sip_call_id):
        """Sets the sip_call_id of this RealTimeSipCallStartEvent.


        :param sip_call_id: The sip_call_id of this RealTimeSipCallStartEvent.  # noqa: E501
        :type: int
        """

        self._sip_call_id = sip_call_id

    @property
    def association_id(self):
        """Gets the association_id of this RealTimeSipCallStartEvent.  # noqa: E501


        :return: The association_id of this RealTimeSipCallStartEvent.  # noqa: E501
        :rtype: int
        """
        return self._association_id

    @association_id.setter
    def association_id(self, association_id):
        """Sets the association_id of this RealTimeSipCallStartEvent.


        :param association_id: The association_id of this RealTimeSipCallStartEvent.  # noqa: E501
        :type: int
        """

        self._association_id = association_id

    @property
    def mac_address(self):
        """Gets the mac_address of this RealTimeSipCallStartEvent.  # noqa: E501


        :return: The mac_address of this RealTimeSipCallStartEvent.  # noqa: E501
        :rtype: MacAddress
        """
        return self._mac_address

    @mac_address.setter
    def mac_address(self, mac_address):
        """Sets the mac_address of this RealTimeSipCallStartEvent.


        :param mac_address: The mac_address of this RealTimeSipCallStartEvent.  # noqa: E501
        :type: MacAddress
        """

        self._mac_address = mac_address

    @property
    def radio_type(self):
        """Gets the radio_type of this RealTimeSipCallStartEvent.  # noqa: E501


        :return: The radio_type of this RealTimeSipCallStartEvent.  # noqa: E501
        :rtype: RadioType
        """
        return self._radio_type

    @radio_type.setter
    def radio_type(self, radio_type):
        """Sets the radio_type of this RealTimeSipCallStartEvent.


        :param radio_type: The radio_type of this RealTimeSipCallStartEvent.  # noqa: E501
        :type: RadioType
        """

        self._radio_type = radio_type

    @property
    def channel(self):
        """Gets the channel of this RealTimeSipCallStartEvent.  # noqa: E501


        :return: The channel of this RealTimeSipCallStartEvent.  # noqa: E501
        :rtype: int
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this RealTimeSipCallStartEvent.


        :param channel: The channel of this RealTimeSipCallStartEvent.  # noqa: E501
        :type: int
        """

        self._channel = channel

    @property
    def codecs(self):
        """Gets the codecs of this RealTimeSipCallStartEvent.  # noqa: E501


        :return: The codecs of this RealTimeSipCallStartEvent.  # noqa: E501
        :rtype: list[str]
        """
        return self._codecs

    @codecs.setter
    def codecs(self, codecs):
        """Sets the codecs of this RealTimeSipCallStartEvent.


        :param codecs: The codecs of this RealTimeSipCallStartEvent.  # noqa: E501
        :type: list[str]
        """

        self._codecs = codecs

    @property
    def provider_domain(self):
        """Gets the provider_domain of this RealTimeSipCallStartEvent.  # noqa: E501


        :return: The provider_domain of this RealTimeSipCallStartEvent.  # noqa: E501
        :rtype: str
        """
        return self._provider_domain

    @provider_domain.setter
    def provider_domain(self, provider_domain):
        """Sets the provider_domain of this RealTimeSipCallStartEvent.


        :param provider_domain: The provider_domain of this RealTimeSipCallStartEvent.  # noqa: E501
        :type: str
        """

        self._provider_domain = provider_domain

    @property
    def device_info(self):
        """Gets the device_info of this RealTimeSipCallStartEvent.  # noqa: E501


        :return: The device_info of this RealTimeSipCallStartEvent.  # noqa: E501
        :rtype: str
        """
        return self._device_info

    @device_info.setter
    def device_info(self, device_info):
        """Sets the device_info of this RealTimeSipCallStartEvent.


        :param device_info: The device_info of this RealTimeSipCallStartEvent.  # noqa: E501
        :type: str
        """

        self._device_info = device_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RealTimeSipCallStartEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RealTimeSipCallStartEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
