# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RealTimeStreamingStopEvent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'model_type': 'str',
        'all_of': 'RealTimeEvent',
        'video_session_id': 'int',
        'session_id': 'int',
        'client_mac': 'MacAddress',
        'server_ip': 'str',
        'total_bytes': 'int',
        'type': 'StreamingVideoType',
        'duration_in_secs': 'int'
    }

    attribute_map = {
        'model_type': 'model_type',
        'all_of': 'allOf',
        'video_session_id': 'videoSessionId',
        'session_id': 'sessionId',
        'client_mac': 'clientMac',
        'server_ip': 'serverIp',
        'total_bytes': 'totalBytes',
        'type': 'type',
        'duration_in_secs': 'durationInSecs'
    }

    def __init__(self, model_type=None, all_of=None, video_session_id=None, session_id=None, client_mac=None, server_ip=None, total_bytes=None, type=None, duration_in_secs=None):  # noqa: E501
        """RealTimeStreamingStopEvent - a model defined in Swagger"""  # noqa: E501
        self._model_type = None
        self._all_of = None
        self._video_session_id = None
        self._session_id = None
        self._client_mac = None
        self._server_ip = None
        self._total_bytes = None
        self._type = None
        self._duration_in_secs = None
        self.discriminator = None
        self.model_type = model_type
        if all_of is not None:
            self.all_of = all_of
        if video_session_id is not None:
            self.video_session_id = video_session_id
        if session_id is not None:
            self.session_id = session_id
        if client_mac is not None:
            self.client_mac = client_mac
        if server_ip is not None:
            self.server_ip = server_ip
        if total_bytes is not None:
            self.total_bytes = total_bytes
        if type is not None:
            self.type = type
        if duration_in_secs is not None:
            self.duration_in_secs = duration_in_secs

    @property
    def model_type(self):
        """Gets the model_type of this RealTimeStreamingStopEvent.  # noqa: E501


        :return: The model_type of this RealTimeStreamingStopEvent.  # noqa: E501
        :rtype: str
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type):
        """Sets the model_type of this RealTimeStreamingStopEvent.


        :param model_type: The model_type of this RealTimeStreamingStopEvent.  # noqa: E501
        :type: str
        """
        if model_type is None:
            raise ValueError("Invalid value for `model_type`, must not be `None`")  # noqa: E501

        self._model_type = model_type

    @property
    def all_of(self):
        """Gets the all_of of this RealTimeStreamingStopEvent.  # noqa: E501


        :return: The all_of of this RealTimeStreamingStopEvent.  # noqa: E501
        :rtype: RealTimeEvent
        """
        return self._all_of

    @all_of.setter
    def all_of(self, all_of):
        """Sets the all_of of this RealTimeStreamingStopEvent.


        :param all_of: The all_of of this RealTimeStreamingStopEvent.  # noqa: E501
        :type: RealTimeEvent
        """

        self._all_of = all_of

    @property
    def video_session_id(self):
        """Gets the video_session_id of this RealTimeStreamingStopEvent.  # noqa: E501


        :return: The video_session_id of this RealTimeStreamingStopEvent.  # noqa: E501
        :rtype: int
        """
        return self._video_session_id

    @video_session_id.setter
    def video_session_id(self, video_session_id):
        """Sets the video_session_id of this RealTimeStreamingStopEvent.


        :param video_session_id: The video_session_id of this RealTimeStreamingStopEvent.  # noqa: E501
        :type: int
        """

        self._video_session_id = video_session_id

    @property
    def session_id(self):
        """Gets the session_id of this RealTimeStreamingStopEvent.  # noqa: E501


        :return: The session_id of this RealTimeStreamingStopEvent.  # noqa: E501
        :rtype: int
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this RealTimeStreamingStopEvent.


        :param session_id: The session_id of this RealTimeStreamingStopEvent.  # noqa: E501
        :type: int
        """

        self._session_id = session_id

    @property
    def client_mac(self):
        """Gets the client_mac of this RealTimeStreamingStopEvent.  # noqa: E501


        :return: The client_mac of this RealTimeStreamingStopEvent.  # noqa: E501
        :rtype: MacAddress
        """
        return self._client_mac

    @client_mac.setter
    def client_mac(self, client_mac):
        """Sets the client_mac of this RealTimeStreamingStopEvent.


        :param client_mac: The client_mac of this RealTimeStreamingStopEvent.  # noqa: E501
        :type: MacAddress
        """

        self._client_mac = client_mac

    @property
    def server_ip(self):
        """Gets the server_ip of this RealTimeStreamingStopEvent.  # noqa: E501

        string representing InetAddress  # noqa: E501

        :return: The server_ip of this RealTimeStreamingStopEvent.  # noqa: E501
        :rtype: str
        """
        return self._server_ip

    @server_ip.setter
    def server_ip(self, server_ip):
        """Sets the server_ip of this RealTimeStreamingStopEvent.

        string representing InetAddress  # noqa: E501

        :param server_ip: The server_ip of this RealTimeStreamingStopEvent.  # noqa: E501
        :type: str
        """

        self._server_ip = server_ip

    @property
    def total_bytes(self):
        """Gets the total_bytes of this RealTimeStreamingStopEvent.  # noqa: E501


        :return: The total_bytes of this RealTimeStreamingStopEvent.  # noqa: E501
        :rtype: int
        """
        return self._total_bytes

    @total_bytes.setter
    def total_bytes(self, total_bytes):
        """Sets the total_bytes of this RealTimeStreamingStopEvent.


        :param total_bytes: The total_bytes of this RealTimeStreamingStopEvent.  # noqa: E501
        :type: int
        """

        self._total_bytes = total_bytes

    @property
    def type(self):
        """Gets the type of this RealTimeStreamingStopEvent.  # noqa: E501


        :return: The type of this RealTimeStreamingStopEvent.  # noqa: E501
        :rtype: StreamingVideoType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RealTimeStreamingStopEvent.


        :param type: The type of this RealTimeStreamingStopEvent.  # noqa: E501
        :type: StreamingVideoType
        """

        self._type = type

    @property
    def duration_in_secs(self):
        """Gets the duration_in_secs of this RealTimeStreamingStopEvent.  # noqa: E501


        :return: The duration_in_secs of this RealTimeStreamingStopEvent.  # noqa: E501
        :rtype: int
        """
        return self._duration_in_secs

    @duration_in_secs.setter
    def duration_in_secs(self, duration_in_secs):
        """Sets the duration_in_secs of this RealTimeStreamingStopEvent.


        :param duration_in_secs: The duration_in_secs of this RealTimeStreamingStopEvent.  # noqa: E501
        :type: int
        """

        self._duration_in_secs = duration_in_secs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RealTimeStreamingStopEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RealTimeStreamingStopEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
