# coding: utf-8

"""
    CloudSDK Portal API

    APIs that provide services for provisioning, monitoring, and history retrieval of various data elements of CloudSDK.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Status(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'model_type': 'str',
        'customer_id': 'int',
        'equipment_id': 'int',
        'status_data_type': 'StatusDataType',
        'status_details': 'StatusDetails',
        'created_timestamp': 'int',
        'last_modified_timestamp': 'int'
    }

    attribute_map = {
        'model_type': 'model_type',
        'customer_id': 'customerId',
        'equipment_id': 'equipmentId',
        'status_data_type': 'statusDataType',
        'status_details': 'statusDetails',
        'created_timestamp': 'createdTimestamp',
        'last_modified_timestamp': 'lastModifiedTimestamp'
    }

    def __init__(self, model_type=None, customer_id=None, equipment_id=None, status_data_type=None, status_details=None, created_timestamp=None, last_modified_timestamp=None):  # noqa: E501
        """Status - a model defined in Swagger"""  # noqa: E501
        self._model_type = None
        self._customer_id = None
        self._equipment_id = None
        self._status_data_type = None
        self._status_details = None
        self._created_timestamp = None
        self._last_modified_timestamp = None
        self.discriminator = None
        if model_type is not None:
            self.model_type = model_type
        if customer_id is not None:
            self.customer_id = customer_id
        if equipment_id is not None:
            self.equipment_id = equipment_id
        if status_data_type is not None:
            self.status_data_type = status_data_type
        if status_details is not None:
            self.status_details = status_details
        if created_timestamp is not None:
            self.created_timestamp = created_timestamp
        if last_modified_timestamp is not None:
            self.last_modified_timestamp = last_modified_timestamp

    @property
    def model_type(self):
        """Gets the model_type of this Status.  # noqa: E501


        :return: The model_type of this Status.  # noqa: E501
        :rtype: str
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type):
        """Sets the model_type of this Status.


        :param model_type: The model_type of this Status.  # noqa: E501
        :type: str
        """
        allowed_values = ["Status"]  # noqa: E501
        if model_type not in allowed_values:
            raise ValueError(
                "Invalid value for `model_type` ({0}), must be one of {1}"  # noqa: E501
                .format(model_type, allowed_values)
            )

        self._model_type = model_type

    @property
    def customer_id(self):
        """Gets the customer_id of this Status.  # noqa: E501


        :return: The customer_id of this Status.  # noqa: E501
        :rtype: int
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """Sets the customer_id of this Status.


        :param customer_id: The customer_id of this Status.  # noqa: E501
        :type: int
        """

        self._customer_id = customer_id

    @property
    def equipment_id(self):
        """Gets the equipment_id of this Status.  # noqa: E501


        :return: The equipment_id of this Status.  # noqa: E501
        :rtype: int
        """
        return self._equipment_id

    @equipment_id.setter
    def equipment_id(self, equipment_id):
        """Sets the equipment_id of this Status.


        :param equipment_id: The equipment_id of this Status.  # noqa: E501
        :type: int
        """

        self._equipment_id = equipment_id

    @property
    def status_data_type(self):
        """Gets the status_data_type of this Status.  # noqa: E501


        :return: The status_data_type of this Status.  # noqa: E501
        :rtype: StatusDataType
        """
        return self._status_data_type

    @status_data_type.setter
    def status_data_type(self, status_data_type):
        """Sets the status_data_type of this Status.


        :param status_data_type: The status_data_type of this Status.  # noqa: E501
        :type: StatusDataType
        """

        self._status_data_type = status_data_type

    @property
    def status_details(self):
        """Gets the status_details of this Status.  # noqa: E501


        :return: The status_details of this Status.  # noqa: E501
        :rtype: StatusDetails
        """
        return self._status_details

    @status_details.setter
    def status_details(self, status_details):
        """Sets the status_details of this Status.


        :param status_details: The status_details of this Status.  # noqa: E501
        :type: StatusDetails
        """

        self._status_details = status_details

    @property
    def created_timestamp(self):
        """Gets the created_timestamp of this Status.  # noqa: E501


        :return: The created_timestamp of this Status.  # noqa: E501
        :rtype: int
        """
        return self._created_timestamp

    @created_timestamp.setter
    def created_timestamp(self, created_timestamp):
        """Sets the created_timestamp of this Status.


        :param created_timestamp: The created_timestamp of this Status.  # noqa: E501
        :type: int
        """

        self._created_timestamp = created_timestamp

    @property
    def last_modified_timestamp(self):
        """Gets the last_modified_timestamp of this Status.  # noqa: E501

        This class does not perform checks against concurrrent updates. Here last update always wins.  # noqa: E501

        :return: The last_modified_timestamp of this Status.  # noqa: E501
        :rtype: int
        """
        return self._last_modified_timestamp

    @last_modified_timestamp.setter
    def last_modified_timestamp(self, last_modified_timestamp):
        """Sets the last_modified_timestamp of this Status.

        This class does not perform checks against concurrrent updates. Here last update always wins.  # noqa: E501

        :param last_modified_timestamp: The last_modified_timestamp of this Status.  # noqa: E501
        :type: int
        """

        self._last_modified_timestamp = last_modified_timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Status, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Status):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
