name: Test new ARCv2 runners

defaults:
  run:
    shell: bash

env:
  AWS_EKS_NAME: tip-openlan-lab
  AWS_DEFAULT_OUTPUT: json
  AWS_DEFAULT_REGION: ap-south-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CLIENT_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CLIENT_KEY }}

on:
  workflow_dispatch:
    inputs:
      environment:
        default: 'qa01'
        description: 'In which environment OWGW must be restarted (qa01 will restart OWGW in openwifi-qa01)'
        required: true

jobs:
  test-runner:
    runs-on: tip-openlan-lab-runners
    steps:
    - uses: actions/checkout@v4

    - name: install needed tools - aws cli, kubectl
      working-directory: utils
      run: ./installer

    - name: Fetch kubeconfig
      run: aws eks update-kubeconfig --name ${{ env.AWS_EKS_NAME }}

    - name: Lists all pods
      run: kubectl get pods -n openwifi-${{ github.event.inputs.environment }} -o wide

  test-runner-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install needed tools - aws cli, kubectl
      working-directory: utils
      run: ./installer

    - name: Fetch kubeconfig
      run: aws eks update-kubeconfig --name ${{ env.AWS_EKS_NAME }}

    - name: Lists all pods
      run: kubectl get pods -n openwifi-${{ github.event.inputs.environment }} -o wide
